# Generated by Django 4.1.5 on 2023-01-03 20:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
            ],
            options={
                'db_table': 'espacios',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^(\\d{1,3}(?:.\\d{1,3}){2}-[\\dkK])$', message='Rut no válido')])),
                ('correo', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'profesores',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
                ('espacio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.espacio')),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.estudiante')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.profesor')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
    ]
